version: "3"

services:
  social:
    image: trustdemocracy/social
    build: ../social
    ports:
      - "8080:8080"

  votes:
    image: trustdemocracy/votes
    build: ../votes
    ports:
      - "8081:8080"

  ranker:
    image: trustdemocracy/ranker
    build: ../ranker
    ports:
      - "8082:8080"

  proposals:
    image: trustdemocracy/proposals
    build: ../proposals
    ports:
      - "8083:8080"

  users:
    image: trustdemocracy/users
    build: ../users
    ports:
      - "8084:8080"

  client:
    image: trustdemocracy/client
    build:
      context: ../client
      dockerfile: .docker/Dockerfile
    ports:
      - "80:80"
