version: "3"

services:
  social:
    image: trustdemocracy/social
    build: ../social
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  votes:
    image: trustdemocracy/votes
    build: ../votes
    ports:
      - "8081:8080"
    depends_on:
      - mysql

  ranker:
    image: trustdemocracy/ranker
    build: ../ranker
    ports:
      - "8082:8080"
    depends_on:
      - mongo

  proposals:
    image: trustdemocracy/proposals
    build: ../proposals
    ports:
      - "8083:8080"
    depends_on:
      - mysql

  users:
    image: trustdemocracy/users
    build: ../users
    ports:
      - "8084:8080"
    depends_on:
      - mongo
    environment:
      - db_host=mongo

  client:
    image: trustdemocracy/client
    build:
      context: ../client
      dockerfile: .docker/Dockerfile
    ports:
      - "80:80"

  mongo:
    image: mongo:latest
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27017:27017"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
