version: "3"

services:
  social:
    image: trustdemocracy/social
    build: ../social
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ./keys:/keys
    environment:
      - db_host=mongo
      - private_key=/keys/private_key.der
      - public_key=/keys/public_key.der

  votes:
    image: trustdemocracy/votes
    build: ../votes
    ports:
      - "8081:8080"
    depends_on:
      - mysql

  ranker:
    image: trustdemocracy/ranker
    build: ../ranker
    ports:
      - "8082:8080"
    depends_on:
      - mongo

  proposals:
    image: trustdemocracy/proposals
    build: ../proposals
    ports:
      - "8083:8080"
    depends_on:
      - mysql
    volumes:
      - ./keys:/keys
    environment:
      - db_url=jdbc:mysql://mysql:3306/proposals
      - db_username=root
      - db_password=root
      - private_key=/keys/private_key.der
      - public_key=/keys/public_key.der
      - social_host=social
      - social_port=8080

  users:
    image: trustdemocracy/users
    build: ../users
    ports:
      - "8084:8080"
    depends_on:
      - mongo
    volumes:
      - ./keys:/keys
    environment:
      - db_host=mongo
      - private_key=/keys/private_key.der
      - public_key=/keys/public_key.der

  mongo:
    image: mongo:latest
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27017:27017"

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=proposals
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  nginx:
    image: nginx
    volumes:
      - ./init/nginx/conf.d:/etc/nginx/conf.d
      - ../client/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - users
      - proposals
      - social
    environment:
      - NGINX_HOST=trustdemocracy.dev
      - NGINX_PORT=80
